// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/polylabel/index.d.ts
declare module "polylabel" {
    /**
     * Polylabel returns the pole of inaccessibility coordinate in [x, y] format.
     * 
     * @name polylabel
     * @function
     * @param {Array<number>} polygon - Given polygon coordinates in GeoJSON-like format
     * @param {number} precision - Precision (1.0 by default)
     * @param {boolean} debug - Debugging for Console 
     * @return {Array<number>}
     * @example
     * var p = polylabel(polygon, 1.0);
     */
    function polylabel(polygon: number[][][], precision?: number, debug?: boolean): number[];
    namespace polylabel {}
    export = polylabel;
}
